[versions]
agp = "9.0.1"
spotless = "8.2.1"
supportAnnotations = "28.0.0"

[libraries]
support-annotations = { module = "com.android.support:support-annotations", version.ref = "supportAnnotations" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
