[versions]
agp = "8.13.0"
spotless = "8.1.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
